package com.kairumo.padnote

/** ⚠️ 這是產生檔，不要手改。來源：i18n/core-patterns.json（樣式）與 i18n/ui-strings.json（譯文），改完跑 python3 scripts/i18n_tool.py generate。 */
object CoreMessagePatterns {
    /** (譯文鍵, 以動態片段切開的固定文字)。依固定字多寡由多到少排列。 */
    val all: List<Pair<String, List<String>>> = listOf(
        "core_msg_195" to listOf("這本筆記是在復原碼還不能解鎖的版本建立的 —— 它的復原碼從來沒有被用來包住金鑰，只有密碼開得了"),
        "log_msg_031" to listOf("📊【同步前核實】本機 ", " 本，清理 ", " 本，有差異待同步 ", " 本（跳過 ", " 本）"),
        "core_msg_161" to listOf("revision 必須是實際的 commit sha，不能是浮動參照：", ""),
        "log_msg_017" to listOf("【Google Drive 同步】等待上一輪結束逾時，已保留待同步狀態"),
        "core_msg_035" to listOf("備份檔版本 ", " 比這個版本的 App 新（支援到 ", "），請先更新 App"),
        "core_msg_204" to listOf("Google Drive 不支援 append（", "）；請改用分塊檔策略"),
        "log_msg_072" to listOf("【焦點同步】", "… 上傳 ", "、下載 ", "（匯出 ", "ms、雲端 ", "ms、匯入 ", "ms）"),
        "log_msg_081" to listOf("自動清理：暫存 ", " 項、模型殘檔 ", " 項（共 ", " MB），回收桶期滿 ", " 本"),
        "log_msg_018" to listOf("【Google Drive 同步】上一輪（", "）卡了 ", " 秒沒收尾，接手"),
        "log_msg_033" to listOf("【前台極速軌】當前筆記 (", "...) 完成（上傳: ", ", 下載: ", "）"),
        "core_msg_205" to listOf("Drive API 速率限制（HTTP 403），稍後重試：", ""),
        "log_msg_003" to listOf("Google 授權失敗：缺少 Code 或 Verifier"),
        "log_msg_027" to listOf("步驟 2 完成。上傳: ", ", 下載: ", ", 新增: ", ", 失敗: ", ""),
        "log_msg_036" to listOf("【背景佇列】筆記本 (", "...) 完成（上傳: ", ", 下載: ", "）"),
        "core_msg_100" to listOf("房間金鑰格式錯誤（需要 base64 的 32 位元組）"),
        "core_msg_200" to listOf("oplog 操作筆數超過上限，已終止載入以防止記憶體溢出"),
        "log_msg_026" to listOf("步驟 2：更新雲端快照（changes.list）..."),
        "log_msg_030" to listOf("📊【同步前核實】本機現存: ", " 本，待同步活躍筆記: ", " 本"),
        "log_msg_065" to listOf("【回收】刪除 ", " 個，失敗 ", " 個：", "；", " 本在等這些裝置確認：", ""),
        "log_msg_009" to listOf("【同步中斷】已送出中斷要求，正在終止進行中的任務..."),
        "log_msg_016" to listOf("【資料夾同步】", " 完成。上傳: ", ", 下載: ", ", 失敗: ", ""),
        "log_msg_032" to listOf("【前台極速軌】優先同步當前作用中筆記 (", "...)..."),
        "core_msg_163" to listOf("授權檔只有 ", " bytes，多半不是授權文本而是錯誤頁"),
        "core_msg_223" to listOf("雲端尚無此筆記本之操作記錄，已清理暫存等待來源端上傳"),
        "log_msg_008" to listOf("無法取得有效權杖，Google Drive 同步中止"),
        "log_msg_063" to listOf("【回收】完成，刪除 ", " 個檔案；", " 本在等這些裝置確認：", ""),
        "core_msg_202" to listOf("Drive 沒有回傳 startPageToken"),
        "log_msg_010" to listOf("【資料夾同步】等待上一輪結束逾時，已保留待同步狀態"),
        "core_msg_188" to listOf("此筆記本需要版本 ", " 的讀取器，本程式為 ", "，請升級"),
        "log_msg_028" to listOf("步驟 2 完成。上傳: ", ", 下載: ", ", 新增: ", ""),
        "log_msg_034" to listOf("【背景佇列】開始同步其餘 ", " 本非作用中筆記..."),
        "core_msg_096" to listOf("熵長度須為 16 或 32 bytes，實得 ", ""),
        "core_msg_158" to listOf("模型校驗失敗：期望 ", "…，實得 ", "…（檔案已刪除）"),
        "log_msg_004" to listOf("Google 授權驗證失敗：State 不符合"),
        "log_msg_011" to listOf("【資料夾同步】上一輪（", "）卡了 ", " 秒沒收尾，接手"),
        "log_msg_020" to listOf("【Google Drive 同步】已手動中斷。"),
        "log_msg_024" to listOf("步驟 1：同步中繼資料與索引 (連線中)..."),
        "log_msg_025" to listOf("步驟 2：搬移雲端檔案 (雙軌並行排程)..."),
        "log_msg_038" to listOf("無法取得 Google Drive 工作階段！"),
        "log_msg_047" to listOf("筆記本 ", "… 正在被焦點同步佔用，這一輪略過匯入"),
        "log_msg_015" to listOf("【資料夾同步】失敗：無法在遠端建立套件目錄 ", ""),
        "log_msg_021" to listOf("【Google Drive 同步】全部完成。"),
        "log_msg_035" to listOf("【背景佇列】開始同步筆記本 (", "...)..."),
        "log_msg_073" to listOf("【焦點同步】", "… 上傳 ", "、下載 ", "（雲端 ", "ms）"),
        "core_msg_033" to listOf("此平台版本未啟用 Whisper 語音引擎"),
        "core_msg_099" to listOf("復原碼校驗失敗，請檢查是否抄錯字或順序有誤"),
        "core_msg_139" to listOf("找不到投影片；可能不是 pptx 或已加密"),
        "log_msg_019" to listOf("【Google Drive 同步】開始執行"),
        "log_msg_039" to listOf("無法取得 Google Drive 索引！"),
        "log_msg_067" to listOf("【重置雲端】等待上一輪結束逾時，請稍後重試"),
        "log_msg_080" to listOf("自動清理：", " 項（", " MB），回收桶期滿 ", " 本"),
        "core_msg_203" to listOf("建立 ", " 之後 Drive 沒有回傳 id"),
        "log_msg_001" to listOf("Google 帳號授權成功！已儲存憑證。"),
        "log_msg_006" to listOf("正在向 Google 交換授權憑證..."),
        "log_msg_052" to listOf("發現新筆記「", "」(", ")，開始自雲端下載..."),
        "log_msg_058" to listOf("【回收桶】已永久清理本機 ", " 本過期筆記本"),
        "log_msg_059" to listOf("【回收桶】", " 本已期滿，等待這些裝置確認：", ""),
        "log_msg_060" to listOf("【回收桶】", " 本已期滿，等待這些裝置確認："),
        "core_msg_138" to listOf("不是 ZIP 容器，無法作為 pptx"),
        "core_msg_199" to listOf("這個套件已加密，需要先解鎖才讀得出內容"),
        "core_msg_221" to listOf("停止門檻必須低於開始門檻，否則遲滯失效"),
        "log_msg_022" to listOf("步驟 1：匯出本機筆記 (", " 本)..."),
        "log_msg_057" to listOf("【回收桶】已永久清理雲端 ", " 個過期檔案"),
        "log_msg_061" to listOf("【回收】等待上一輪結束逾時，請稍後重試"),
        "core_msg_011" to listOf("音框長度錯誤：得到 ", " 個樣本，應為 ", ""),
        "core_msg_051" to listOf("Drive 回應不是合法 JSON：", ""),
        "core_msg_159" to listOf("大小不符：期望 ", " bytes，實得 ", ""),
        "core_msg_164" to listOf("model card 未宣告授權名稱"),
        "core_msg_206" to listOf("可續傳上傳沒有回傳 Location"),
        "log_msg_069" to listOf("【重置雲端】刪除 ", " 個，失敗 ", " 個：", ""),
        "core_msg_194" to listOf("salt 不是合法 base64：", ""),
        "log_msg_029" to listOf("步驟 3：匯入套件回本機筆記..."),
        "log_msg_045" to listOf("筆記本 ", "… 完成（上傳 ", "、下載 ", "）"),
        "log_msg_075" to listOf("【區網直連】", "… 忙碌中，稍後再匯入"),
        "log_msg_076" to listOf("【區網直連】", "… 收到並匯入（", "ms）"),
        "core_msg_008" to listOf("ONNX Runtime 錯誤：", ""),
        "core_msg_046" to listOf("金鑰長度不對（要 32 位元組）"),
        "core_msg_071" to listOf("行動端線框 (8pt Grid)"),
        "core_msg_088" to listOf("解密失敗：密語錯誤或資料已被竄改"),
        "core_msg_098" to listOf("詞數須為 12 或 24，實得 ", ""),
        "core_msg_101" to listOf("密文長度不足，不可能是有效的訊息"),
        "core_msg_103" to listOf("解密失敗（金鑰不符或內容被竄改）"),
        "core_msg_141" to listOf("第 ", " 個區塊缺少 content"),
        "log_msg_042" to listOf("雲端變動 ", " 筆，快照共 ", " 個檔案"),
        "log_msg_064" to listOf("【回收】刪除 ", " 個，失敗 ", " 個：", ""),
        "log_msg_068" to listOf("【重置雲端】完成，刪除 ", " 個檔案"),
        "core_msg_118" to listOf("非法的 Unicode 碼位：", ""),
        "core_msg_140" to listOf("第 ", " 個區塊缺少 source"),
        "core_msg_186" to listOf("blob 損毀：期望 ", "，實得 ", ""),
        "core_msg_187" to listOf("不是 .padnote 套件：", ""),
        "log_msg_002" to listOf("Google 授權取消或失敗：", ""),
        "log_msg_012" to listOf("【資料夾同步】開始執行，目標：", ""),
        "log_msg_023" to listOf("步驟 1 完成，成功匯出 ", " 本"),
        "log_msg_066" to listOf("【重置雲端】開始刪除雲端資料…"),
        "log_msg_071" to listOf("【焦點同步】", "… 上傳 ", "、下載 ", ""),
        "log_msg_077" to listOf("【區網直連】", "… 收到對端的更新"),
        "core_msg_029" to listOf("模型檔案不存在或無法載入: ", ""),
        "core_msg_034" to listOf("不是 Kairumo 備份檔"),
        "core_msg_072" to listOf("響應式 Web 12 欄網格"),
        "core_msg_147" to listOf("不是 PADNINK 筆畫檔"),
        "core_msg_155" to listOf("提示詞轉 token 失敗：", ""),
        "core_msg_156" to listOf("建立 context 失敗：", ""),
        "core_msg_170" to listOf("頁碼 ", " 超出範圍（共 ", " 頁）"),
        "core_msg_172" to listOf("找不到 libpdfium：", ""),
        "core_msg_189" to listOf("manifest 解析失敗：", ""),
        "core_msg_198" to listOf("不合法的 oplog 檔名：", ""),
        "log_msg_041" to listOf("雲端快照重建完成（", " 個檔案）"),
        "log_msg_053" to listOf("筆記本「", "」成功自雲端下載完成"),
        "log_msg_055" to listOf("已清理已刪除筆記本殘留套件：", ""),
        "log_msg_056" to listOf("【回收桶】確認檔沒發布成功：", ""),
        "log_msg_062" to listOf("【回收】完成，刪除 ", " 個檔案"),
        "log_msg_079" to listOf("【區網直連】已連上 ", " 台裝置"),
        "core_msg_024" to listOf("blob id 無法解析：", ""),
        "core_msg_025" to listOf("變換矩陣必須是 6 個數字"),
        "core_msg_095" to listOf("詞表必須是 ", " 個詞，實得 ", ""),
        "core_msg_117" to listOf("字串不是合法的 UTF-8"),
        "core_msg_182" to listOf("房主已結束本次線上協同會議"),
        "core_msg_217" to listOf("第一個訊框不是 Ready"),
        "log_msg_005" to listOf("授權失敗：未收到重導向資料"),
        "log_msg_013" to listOf("【資料夾同步】已手動中斷。"),
        "log_msg_054" to listOf("筆記本「", "」自雲端下載失敗：", ""),
        "core_msg_053" to listOf("讀不到本機 oplog：", ""),
        "core_msg_069" to listOf("30° 等角立體軸測網格"),
        "core_msg_142" to listOf("第 ", " 個區塊的類型未知：", ""),
        "core_msg_143" to listOf("筆記本內無任何頁面可匯出"),
        "core_msg_150" to listOf("未知的 tool_id：", ""),
        "core_msg_177" to listOf("logits 維度為 0"),
        "log_msg_014" to listOf("【資料夾同步】全部完成。"),
        "core_msg_004" to listOf("標點模型尚未下載或載入"),
        "core_msg_009" to listOf("am.mvn 解析失敗"),
        "core_msg_015" to listOf("圖表的資料數列都是空的"),
        "core_msg_044" to listOf("密碼錯誤或資料已被竄改"),
        "core_msg_166" to listOf("產出檔案雜湊格式錯誤：", ""),
        "core_msg_168" to listOf("不是有效的 PDF 檔"),
        "core_msg_169" to listOf("這份 PDF 需要密碼"),
        "core_msg_180" to listOf("密碼錯誤，無法加入房間"),
        "core_msg_222" to listOf("找不到 VAD 模型：", ""),
        "log_msg_046" to listOf("筆記本 ", "… 同步失敗：", ""),
        "log_msg_070" to listOf("【焦點同步】", "… 失敗：", ""),
        "log_msg_078" to listOf("【區網直連】啟動失敗：", ""),
        "core_msg_010" to listOf("Opus 編碼失敗：", ""),
        "core_msg_014" to listOf("圖表沒有任何資料數列"),
        "core_msg_041" to listOf("讀不到舊套件的操作：", ""),
        "core_msg_060" to listOf("清單裡沒有這個模型：", ""),
        "core_msg_065" to listOf("極細點陣 (5mm)"),
        "core_msg_107" to listOf("物件已屬於其他群組：", ""),
        "core_msg_157" to listOf("decode 失敗：", ""),
        "core_msg_162" to listOf("授權檔雜湊格式錯誤：", ""),
        "core_msg_176" to listOf("詞表缺少 <unk>"),
        "core_msg_181" to listOf("僅房主有權關閉此房間"),
        "core_msg_196" to listOf("不合法的裝置 id：", ""),
        "core_msg_210" to listOf("方向不符（疑似反射）"),
        "core_msg_215" to listOf("對端裝置 id 不符"),
        "core_msg_220" to listOf("檔案尚未從雲端下載：", ""),
        "log_msg_050" to listOf("筆記本 ", " 同步失敗：", ""),
        "core_msg_001" to listOf("模型尚未下載或載入"),
        "core_msg_007" to listOf("模型資源格式錯誤：", ""),
        "core_msg_013" to listOf("圖表設定格式錯誤：", ""),
        "core_msg_022" to listOf("簡報（", " 張投影片）"),
        "core_msg_023" to listOf("簡報（無法讀取：", "）"),
        "core_msg_028" to listOf("不是合法的 id：", ""),
        "core_msg_050" to listOf("網路或伺服器錯誤：", ""),
        "core_msg_066" to listOf("黃金比例與三分構圖"),
        "core_msg_073" to listOf("使用者旅程與流程圖"),
        "core_msg_074" to listOf("無法建立執行緒池：", ""),
        "core_msg_108" to listOf("文件操作資料被截斷"),
        "core_msg_115" to listOf("未知的連接線路由：", ""),
        "core_msg_148" to listOf("不支援的格式版本：", ""),
        "core_msg_152" to listOf("沒有可以處理的文字"),
        "core_msg_160" to listOf("模型清單格式錯誤：", ""),
        "core_msg_167" to listOf("缺少工具版本紀錄：", ""),
        "core_msg_171" to listOf("PDF 引擎錯誤：", ""),
        "core_msg_184" to listOf("無法解析之訊息格式"),
        "core_msg_185" to listOf("找不到 blob：", ""),
        "core_msg_190" to listOf("文件操作日誌損毀：", ""),
        "core_msg_197" to listOf("不合法的錄音檔名：", ""),
        "core_msg_219" to listOf("不該由這一方連過來"),
        "log_msg_040" to listOf("雲端快照更新失敗：", ""),
        "log_msg_044" to listOf("中繼資料同步失敗：", ""),
        "log_msg_049" to listOf("筆記本 ", " 同步中斷"),
        "core_msg_027" to listOf("找不到指定頁面：", ""),
        "core_msg_030" to listOf("轉錄處理失敗: ", ""),
        "core_msg_031" to listOf("音訊資料無效: ", ""),
        "core_msg_032" to listOf("音訊資料長度為零"),
        "core_msg_038" to listOf("索引長度超出檔案"),
        "core_msg_047" to listOf("起不了區網節點：", ""),
        "core_msg_056" to listOf("讀不到本機筆跡：", ""),
        "core_msg_067" to listOf("情緒板與色卡矩陣"),
        "core_msg_070" to listOf("三視圖與剖面範本"),
        "core_msg_077" to listOf("取不到綁定的埠：", ""),
        "core_msg_078" to listOf("設定非阻塞失敗：", ""),
        "core_msg_079" to listOf("中繼狀態鎖已毀損"),
        "core_msg_092" to listOf("DEK 長度錯誤"),
        "core_msg_094" to listOf("chunk 過短"),
        "core_msg_109" to listOf("未知的操作類型：", ""),
        "core_msg_110" to listOf("未知的頁面模板：", ""),
        "core_msg_111" to listOf("未知的文字樣式：", ""),
        "core_msg_112" to listOf("未知的物件類型：", ""),
        "core_msg_113" to listOf("未知的形狀類型：", ""),
        "core_msg_116" to listOf("未知的線端樣式：", ""),
        "core_msg_151" to listOf("未知的記錄類型：", ""),
        "core_msg_165" to listOf("沒有任何產出檔案"),
        "core_msg_173" to listOf("找不到標點模型：", ""),
        "core_msg_178" to listOf("辨識後端不可用：", ""),
        "core_msg_193" to listOf("這個套件沒有加密"),
        "core_msg_201" to listOf("路徑包含非法穿越"),
        "core_msg_212" to listOf("標頭不是合法訊息"),
        "log_msg_037" to listOf("匯出失敗 (", ")：", ""),
        "log_msg_043" to listOf("元資料同步失敗：", ""),
        "log_msg_074" to listOf("【焦點同步】", "… ", ""),
        "core_msg_002" to listOf("不支援的語言：", ""),
        "core_msg_005" to listOf("標點還原失敗：", ""),
        "core_msg_006" to listOf("找不到模型檔：", ""),
        "core_msg_020" to listOf("找不到里程碑：", ""),
        "core_msg_021" to listOf("不支援的格式：", ""),
        "core_msg_036" to listOf("備份檔已損毀：", ""),
        "core_msg_039" to listOf("索引解析失敗：", ""),
        "core_msg_040" to listOf("開不了舊套件：", ""),
        "core_msg_042" to listOf("開不了新套件：", ""),
        "core_msg_043" to listOf("寫不進新套件：", ""),
        "core_msg_045" to listOf("復原碼不正確：", ""),
        "core_msg_057" to listOf("讀不到筆跡 ", "：", ""),
        "core_msg_058" to listOf("寫不進筆跡 ", "：", ""),
        "core_msg_068" to listOf("工程藍圖坐標紙"),
        "core_msg_084" to listOf("AI 模型（", "）"),
        "core_msg_085" to listOf("本機同步資料夾"),
        "core_msg_089" to listOf("金鑰匯出失敗：", ""),
        "core_msg_090" to listOf("亂數來源失敗：", ""),
        "core_msg_091" to listOf("資料格式錯誤：", ""),
        "core_msg_097" to listOf("無法辨識的詞：", ""),
        "core_msg_106" to listOf("群組會形成迴圈"),
        "core_msg_114" to listOf("未知的連接點：", ""),
        "core_msg_129" to listOf("編輯（僅預覽）"),
        "core_msg_136" to listOf("", " 目前不支援：", ""),
        "core_msg_137" to listOf("檔案格式錯誤：", ""),
        "core_msg_144" to listOf("儲存讀取錯誤：", ""),
        "core_msg_145" to listOf("圖片編碼錯誤：", ""),
        "core_msg_153" to listOf("載入模型失敗：", ""),
        "core_msg_154" to listOf("模型狀態已損毀"),
        "core_msg_175" to listOf("詞表格式錯誤：", ""),
        "core_msg_192" to listOf("封裝壓縮錯誤：", ""),
        "log_msg_007" to listOf("交換權杖失敗：", ""),
        "core_msg_012" to listOf("IO 錯誤：", ""),
        "core_msg_016" to listOf("已經在錄音中"),
        "core_msg_017" to listOf("目前沒有錄音"),
        "core_msg_018" to listOf("找不到頁面：", ""),
        "core_msg_019" to listOf("找不到區塊：", ""),
        "core_msg_026" to listOf("變換矩陣無效"),
        "core_msg_052" to listOf("開不了套件：", ""),
        "core_msg_075" to listOf("無效的埠號 ", ""),
        "core_msg_076" to listOf("無法綁定 ", "：", ""),
        "core_msg_081" to listOf("語音辨識權限"),
        "core_msg_083" to listOf("語音模型（", "）"),
        "core_msg_105" to listOf("找不到物件：", ""),
        "core_msg_135" to listOf("找不到檔案：", ""),
        "core_msg_174" to listOf("找不到詞表：", ""),
        "core_msg_191" to listOf("筆畫檔錯誤：", ""),
        "core_msg_208" to listOf("訊框超過上限"),
        "core_msg_211" to listOf("標頭超出訊框"),
        "core_msg_213" to listOf("解析不到位址"),
        "log_msg_048" to listOf("筆記本 ", "… ", ""),
        "core_msg_003" to listOf("後端錯誤：", ""),
        "core_msg_037" to listOf("讀寫失敗：", ""),
        "core_msg_049" to listOf("權限不足：", ""),
        "core_msg_054" to listOf("讀不到 ", "：", ""),
        "core_msg_055" to listOf("寫不進 ", "：", ""),
        "core_msg_059" to listOf("網路錯誤：", ""),
        "core_msg_104" to listOf("取不到亂數"),
        "core_msg_127" to listOf("條件式格式"),
        "core_msg_146" to listOf("資料無效：", ""),
        "core_msg_149" to listOf("檔案被截斷"),
        "core_msg_179" to listOf("無候選結果"),
        "core_msg_183" to listOf("房間不存在"),
        "log_msg_051" to listOf("筆記本 ", " ", ""),
        "core_msg_048" to listOf("找不到：", ""),
        "core_msg_061" to listOf("空白紙張"),
        "core_msg_062" to listOf("方格點陣"),
        "core_msg_063" to listOf("橫線筆記"),
        "core_msg_082" to listOf("手寫辨識"),
        "core_msg_086" to listOf("可以使用"),
        "core_msg_093" to listOf("資料過短"),
        "core_msg_102" to listOf("加密失敗"),
        "core_msg_120" to listOf("浮動圖文"),
        "core_msg_121" to listOf("追蹤修訂"),
        "core_msg_122" to listOf("頁首頁尾"),
        "core_msg_125" to listOf("樞紐分析"),
        "core_msg_128" to listOf("資料驗證"),
        "core_msg_133" to listOf("表單欄位"),
        "core_msg_134" to listOf("數位簽章"),
        "core_msg_207" to listOf("訊框太大"),
        "core_msg_209" to listOf("訊框太短"),
        "core_msg_214" to listOf("魔數不符"),
        "core_msg_216" to listOf("金鑰不符"),
        "core_msg_218" to listOf("標籤不符"),
        "core_msg_064" to listOf("康乃爾"),
        "core_msg_080" to listOf("麥克風"),
        "core_msg_087" to listOf("需要：", ""),
        "core_msg_132" to listOf("備忘稿"),
        "core_msg_119" to listOf("分欄"),
        "core_msg_123" to listOf("註腳"),
        "core_msg_124" to listOf("巨集"),
        "core_msg_126" to listOf("圖表"),
        "core_msg_130" to listOf("動畫"),
        "core_msg_131" to listOf("轉場"),
    )
}
