[package]
name = "padnote-export"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
padnote-doc = { path = "../padnote-doc" }
padnote-ink = { path = "../padnote-ink" }
padnote-pdf = { path = "../padnote-pdf" }
padnote-storage = { path = "../padnote-storage" }

png = { workspace = true }
miniz_oxide = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
